guardian/prnouncer-config

- .github/workflows/editorial-tools.yml
Adds [prnouncer](https://github.com/guardian/actions-prnouncer) configuration for the Editorial Tools team.
As the only user of the [pr-exposer service](https://github.com/guardian/google-chat-bots/blob/main/pr-exposer/README.md), this should allow the team to retire the pr-exposer service. This will allow for a reduced AWS infrastructure, reduced complexity, and reduced maintenance cost.
Monetary reductions are negligible, w/PR-exposer costing ~$0.20/month.
|                        | prnouncer                 | pr-exposer                         |
|------------------------|-----------------------------------|------------------------------------|
| Configuration          | VCS                               | JSON in S3 (Composer account)      |
| Chat Message Frequency | Cron (once daily) …
> Add configuration for Editorial Tools

- .github/workflows/devx-soar.yml
Adds [ssm-scala](https://github.com/guardian/ssm-scala) to monitored repositories as it's currently a DevX Security repo and unmonitored!
> Adds ssm-scala to monitored repositories

- .github/workflows/dotcom.yml
Moves the DCR prannouncer workflow [dotcom-rendering](https://github.com/guardian/dotcom-rendering/blob/main/.github/workflows/prannouncer.yml) to this repo! (also adds Frontend to our repos to announce)
Related PR https://github.com/guardian/dotcom-rendering/pull/6359
> feat: Dotcom PR announcer

- .github/workflows/dotcom.yml
Adds `prnouncer-ignore` to the ignored labels list. Because adding it here will overwrite the default setting (`Stale`), this commit also adds `Stale` to the ignored list to preserve the status quo.
This allows us to mark open, unreviewed PRs to be ignored, without having to mark them as Stale.
> Ignore PRs with the `prnouncer-ignore` label

- .github/workflows/guardian-engineering-site.yml
Adds the [`guardian-engineering-site`](https://github.com/guardian/guardian-engineering-site) repo as a configuration.
That repo has only a handful of maintainers, so PRs will benefit from more visibility.
N/A
More PR reviews.
N/A
N/A
> feat: add guardian-engineering-site config

- .github/workflows/devx-soar.yml
A new repository appears: `guardian/waf`.
> chore: Add a new repository to DevX SOaR

- .github/workflows/devx-soar.yml
Although github lens urls still point to the service catalogue, I'm updating the repo name to avoid confusion
the prnouncer should still list service-catalogue PRs
> Swap github lens for service catalogue

- .github/workflows/dotcom.yml
- adds apps-rendering-api-models and bridget as these are now owned by `@guardian/dotcom-platform`
> Add repos to dotcom

- .github/workflows/dotcom.yml
The [`about-us` repo](https://github.com/guardian/about-us) is part of the WebX (formerly Dotcom) team.
nb. I was thinking about renaming the workflow file to match the new team name, but I'm not sure how github actions determines what 'the same' workflow is and I didn't want to mess with the action's history without understanding that.
> Add 'about-us' repo to dotcom action

- .github/workflows/devx-soar.yml
DevX will be notified if a PR is raised against [privatebin-docker](https://github.com/guardian/privatebin-docker)
> add new privatebin to devx repos

- .github/workflows/newsroom-resilience.yml
Adds [prnouncer](https://github.com/guardian/actions-prnouncer) configuration for the [Newsroom Resilience team](https://github.com/orgs/guardian/teams/newsroom-resilience).
> Adds config for newsroom resilience team

- .github/workflows/newsroom-resilience.yml
Adds the https://github.com/guardian/image-syndication repository for Newsroom Resilience team.
Merge this, observe PRs posted to NR channel.
NR devs are notified of PRs that are in need of review.
> Add image-syndication to newsroom-resilience repos

- .github/workflows/dotcom.yml
`actions-prnouncer` introduced functionality in https://github.com/guardian/actions-prnouncer/pull/19 to show the relative age of each PR.
> Show PR age for dotcom

- .github/workflows/devx-soar.yml
We're doing a lot of work on https://github.com/guardian/slo-alerts at the moment, so I'd like to start receiving reminders about PRs for this repository.
> Add slo-alerts repository to devx-soar.yml

- .github/workflows/devx-soar.yml
Add `show-pr-age` config. See https://github.com/guardian/actions-prnouncer/pull/19.
> Configure `show-pr-age` for DevX SOaR

- .github/workflows/newsroom-resilience.yml
Adds the https://github.com/guardian/crosswordv2 repository owned by the Newsroom Resilience team.
> Add crosswordv2 repository for Newsroom Resilience team

- .github/workflows/newsroom-resilience.yml
Newsroom Resilience is doing work on the [`remote-machines`](https://github.com/guardian/remote-machines) so it will be useful to get notifications.
> Add remote-machines to Newsroom Resilience repos

- .github/workflows/devx-soar.yml
Adds devx as a notification target for the actions-prnouncer repo. It hasn't had any dependency updates in a while and I think this repo probably falls in our remit.
> Add prnouncer as a DevX repo

- .github/workflows/devx-soar.yml
Adding https://github.com/guardian/cq-source-galaxies as a DevX repository.
> fix: Add `guardian/cq-source-galaxies` to DevX SOaR repositories

- .github/workflows/devx-security.yml
Don't alert security team about tracker PRs
> Security team are no longer responsible for tracker

- .github/workflows/devx-soar.yml
Adds the new riffraff-platform repo to the list of repos owned by DevX SoAR
> Add `riffraff-platform` to list of repos owned by DevX SoAR

- .github/workflows/devx-security.yml
- .github/workflows/devx-soar.yml
Updates the links in the Devx SOaR and Security configs to link to the sub-teams as `developer-experience` is deprecated.
> update devx teams in links

- README.md
Adding Engineering Manager access to the README so that developers don't need to wait on DevX to add a workflow.
> Specify in README that EMs can add secrets

- .github/workflows/mobile.yml
This removes [templates](https://github.com/guardian/mobile-apps-article-templates) from PR announcer as we are phasing out support for this repo. 
This adds [mobile apps api models](https://github.com/guardian/mobile-apps-api-models) to the list so we can receive notifications about open PRs
-   [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#screen-reader)
-   [ ] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physical.md#keyboard)
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#contrast)
-   [ ] [The change doesn't use only colour to convey …
> Modify mss repos

- .github/workflows/devx-security.yml
Remove archived repos/repos no longer owned by the security team from the list
> remove irrelevant repos from the list

- .github/workflows/mobile.yml
This changes the name of the repo myguardian-prefs-api to personalised-app-experience to reflect the new name of the repo
-   [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#screen-reader)
-   [ ] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physical.md#keyboard)
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#contrast)
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use-of-colour)
> Update mobile repo list

- .github/workflows/interviews.yml
Reduces the frequency of the prnouncer action for the interviews repo to once per week.
The channel that this action posts to is a very quiet one (as is the repo it monitors), so the last 25 messages are from prnouncer, concerning the same 2 PRs.
This is partly due to the PRs being quite long-lasting, but this seems likely to happen for PR in this repo, which no one really 'owns'. With alerts once per week PRs will still get surfaced, but there will be a bit less noise in the channel, so it seems like a worthwhile tradeoff.
-   [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#screen-reader)
-   [ ] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physical.md#keyboard) …
> Only post once per week

- .github/workflows/devx-security.yml
We want to get notifications before we start work so that they get top priority at the start of the day.
> Reschedule notifications for devx-security space
